apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tdgqa3a5s-python 
  janus-idp.io/tekton: tdgqa3a5s-python
  backstage.io/kubernetes-id: tdgqa3a5s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tdgqa3a5s-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  